/**
 * Project-file exports for coding agents (Pro): AGENTS.md, CLAUDE.md, .claude/agents/*, .cursor/rules, .cursorrules,
 * .github/copilot-instructions.md, Task Master PRD and the structured JSON. Shared by the Studio, /api/v1 and MCP.
 */
import { EXPERTS, MEGA_CHAIN_STEPS } from "./data";
import { buildExpertPrompt, exportClaudeMd, exportCursorRules, exportJSON, paymentNames, projectTypeName } from "./prompt";
import type { Expert, StudioState } from "./types";

type Lang = "TR" | "EN";

const W = {
  EN: {
    agentsIntro: "Instructions for AI coding agents (Codex, Cursor, Claude Code, Copilot, Jules, Amp…) working in this repository. Generated by Prompt.Monster — keep it short and current.",
    project: "Project",
    what: "What",
    type: "Type",
    users: "Users",
    pain: "pain",
    budget: "budget",
    usp: "Why it wins",
    competitors: "Competitors",
    money: "Monetization",
    payments: "Payments",
    compliance: "Compliance",
    stack: "Stack",
    scope: "v1 scope (build in this order)",
    rules: "Working agreements",
    rulesList: [
      "TypeScript strict mode; no `any`. Validate every external input at the boundary (e.g. zod).",
      "Secrets only in environment variables — never in code, logs or the client bundle.",
      "Database changes go through migrations in the repo; row-level security on every table with user data; no N+1 queries.",
      "Authorization is checked on the server for every mutation, never only in the UI.",
      "Every feature ships with tests: unit tests for logic, one end-to-end happy path.",
      "Small, focused commits (conventional commits). Update this file when a convention changes.",
      "No TODOs, placeholders or lorem ipsum — every line production-ready.",
    ],
    done: "Definition of done",
    doneList: ["p95 interaction < 100 ms, Lighthouse 95+", "0 critical vulnerabilities; GDPR/KVKK by design", "The feature's acceptance criteria are met and demonstrated"],
    verify: "Verify before you finish (self-check)",
    verifyList: [
      "It builds with no type errors and lint passes.",
      "Tests pass, and new code is covered.",
      "Every acceptance criterion of the feature is met — re-read the task and check each one.",
      "Inputs are validated, authorization is enforced server-side, no secrets leak.",
      "Edge cases handled: empty, error, loading, slow network, permission denied.",
      "Docs updated (README / this file) when behaviour or setup changed.",
    ],
    experts: "Expert briefs",
    expertsText: "Detailed briefs per expert live in CLAUDE.md and .claude/agents/ (Claude Code subagents).",
    copilotIntro: "Repository instructions for GitHub Copilot. Generated by Prompt.Monster.",
    copilotAbout: "About this project",
    copilotCode: "When generating code",
    agentNote:
      "When invoked: read CLAUDE.md and AGENTS.md first, stay within your specialty, make the smallest change that fully solves the task, then reply with a short report — decisions, files changed, open risks.",
    agentDesc: (e: Expert, name: string, task: string) => `${e.role} for ${name}. Use proactively for ${e.spec} work: ${task}`,
  },
  TR: {
    agentsIntro: "Bu depoda çalışan AI kodlama ajanları (Codex, Cursor, Claude Code, Copilot, Jules, Amp…) için talimatlar. Prompt.Monster ile üretildi — kısa ve güncel tut.",
    project: "Proje",
    what: "Ne",
    type: "Tip",
    users: "Kullanıcılar",
    pain: "acı",
    budget: "bütçe",
    usp: "Neden kazanır",
    competitors: "Rakipler",
    money: "Gelir modeli",
    payments: "Ödeme",
    compliance: "Uyumluluk",
    stack: "Teknoloji",
    scope: "v1 kapsamı (bu sırayla geliştir)",
    rules: "Çalışma kuralları",
    rulesList: [
      "TypeScript strict; `any` yok. Dışarıdan gelen her girdiyi sınırda doğrula (ör. zod).",
      "Gizli anahtarlar yalnız ortam değişkenlerinde — kodda, logda ve istemci paketinde asla.",
      "Veritabanı değişiklikleri depodaki migration'larla; kullanıcı verisi olan her tabloda RLS; N+1 sorgu yok.",
      "Yetki her değişiklikte sunucuda kontrol edilir, yalnız arayüzde değil.",
      "Her özellik testle gelir: mantık için unit test, bir uçtan uca mutlu yol.",
      "Küçük, odaklı commit'ler (conventional commits). Bir kural değişince bu dosyayı güncelle.",
      "TODO, placeholder, lorem ipsum yok — her satır production'a hazır.",
    ],
    done: "Bitti tanımı",
    doneList: ["p95 etkileşim < 100 ms, Lighthouse 95+", "0 kritik açık; KVKK/GDPR tasarımdan itibaren", "Özelliğin kabul kriterleri karşılandı ve gösterildi"],
    verify: "Bitirmeden önce kendini doğrula",
    verifyList: [
      "Tip hatası olmadan derleniyor, lint temiz.",
      "Testler geçiyor, yeni kod testli.",
      "Özelliğin her kabul kriteri karşılandı — görevi yeniden oku ve tek tek kontrol et.",
      "Girdiler doğrulanıyor, yetki sunucuda kontrol ediliyor, gizli bilgi sızmıyor.",
      "Uç durumlar ele alındı: boş, hata, yükleniyor, yavaş ağ, yetkisiz erişim.",
      "Davranış veya kurulum değiştiyse dokümanlar (README / bu dosya) güncellendi.",
    ],
    experts: "Uzman brifleri",
    expertsText: "Uzman başına ayrıntılı brifler CLAUDE.md ve .claude/agents/ (Claude Code alt ajanları) içinde.",
    copilotIntro: "GitHub Copilot için depo talimatları. Prompt.Monster ile üretildi.",
    copilotAbout: "Proje hakkında",
    copilotCode: "Kod üretirken",
    agentNote:
      "Çağrıldığında: önce CLAUDE.md ve AGENTS.md'yi oku, kendi uzmanlık alanında kal, görevi tam çözen en küçük değişikliği yap, sonra kısa bir rapor ver — kararlar, değişen dosyalar, açık riskler.",
    agentDesc: (e: Expert, name: string, task: string) => `${name} projesinin ${e.role} uzmanı. ${e.spec} işleri için proaktif kullan: ${task}`,
  },
} as const;

const trimWords = (t: string, n: number) => {
  const w = t.split(/\s+/).filter(Boolean);
  return w.length > n ? `${w.slice(0, n).join(" ")}…` : w.join(" ");
};

function stackLines(s: StudioState): string[] {
  const rows: [string, string[]][] = [
    ["Frontend", s.frontend],
    ["Backend", s.backend],
    ["Database", s.database],
    ["Auth", s.auth],
    ["AI", s.ai],
    ["Infra / realtime", s.realtime],
    ["Search", s.search],
  ];
  return rows.filter(([, v]) => v.length).map(([k, v]) => `- ${k}: ${v.join(", ")}`);
}

function projectLines(s: StudioState, lang: Lang): string[] {
  const w = W[lang];
  const comp = s.competitors.filter(Boolean);
  return [
    `- ${w.what}: ${trimWords(s.description || s.pitch, 80)}`,
    `- ${w.type}: ${projectTypeName(s.projectType)}`,
    s.audience.role ? `- ${w.users}: ${s.audience.role}${s.audience.pain ? ` — ${w.pain}: ${s.audience.pain}` : ""}${s.audience.budget ? ` — ${w.budget}: ${s.audience.budget}` : ""}` : "",
    s.usp ? `- ${w.usp}: ${s.usp}` : "",
    comp.length ? `- ${w.competitors}: ${comp.join(", ")}` : "",
    s.monetization.length ? `- ${w.money}: ${s.monetization.join(", ")}${s.payments.length ? ` · ${w.payments}: ${paymentNames(s.payments)}` : ""}` : "",
    s.compliance.length ? `- ${w.compliance}: ${s.compliance.join(", ")}` : "",
  ].filter(Boolean);
}

/** AGENTS.md — the cross-tool instructions file (agents.md). `title` overrides the heading (Cursor rules reuse the body). */
export function exportAgentsMd(s: StudioState, title = `AGENTS.md — ${s.name}`): string {
  const w = W[s.lang];
  const stack = stackLines(s);
  return [
    `# ${title}`,
    "",
    s.pitch ? `> ${s.pitch}` : "",
    "",
    w.agentsIntro,
    "",
    `## ${w.project}`,
    ...projectLines(s, s.lang),
    "",
    ...(stack.length ? [`## ${w.stack}`, ...stack, ""] : []),
    ...(s.features.length ? [`## ${w.scope}`, ...s.features.map((f, i) => `${i + 1}. ${f}`), ""] : []),
    `## ${w.rules}`,
    ...w.rulesList.map((r) => `- ${r}`),
    "",
    `## ${w.done}`,
    ...w.doneList.map((r) => `- ${r}`),
    "",
    `## ${w.verify}`,
    ...w.verifyList.map((r) => `- [ ] ${r}`),
    "",
    `## ${w.experts}`,
    w.expertsText,
    "",
  ]
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

/** .github/copilot-instructions.md — short, self-contained statements (what Copilot follows best). */
export function exportCopilotInstructions(s: StudioState): string {
  const w = W[s.lang];
  return [
    `# ${s.name} — Copilot instructions`,
    "",
    w.copilotIntro,
    "",
    `## ${w.copilotAbout}`,
    s.pitch ? `- ${s.pitch}` : "",
    ...projectLines(s, s.lang),
    "",
    ...(stackLines(s).length ? [`## ${w.stack}`, ...stackLines(s), ""] : []),
    `## ${w.copilotCode}`,
    ...w.rulesList.map((r) => `- ${r}`),
    "",
    `## ${w.verify}`,
    ...w.verifyList.map((r) => `- ${r}`),
    "",
  ]
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

/** File-name slug for an expert: "Staff Engineer / CTO" → "staff-engineer-cto". */
export function expertSlug(e: Expert): string {
  return e.role
    .toLowerCase()
    .replace(/&/g, " ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/** .claude/agents/<expert>.md — one Claude Code subagent per selected expert. */
export function exportClaudeAgents(s: StudioState): Record<string, string> {
  const w = W[s.lang];
  const out: Record<string, string> = {};
  for (const id of s.experts) {
    const e = EXPERTS.find((x) => x.id === id);
    if (!e) continue;
    const task = (s.lang === "EN" ? (e.taskEn ?? e.task) : e.task).replace(/\s+/g, " ").trim();
    const description = w.agentDesc(e, s.name, trimWords(task, 28)).replace(/"/g, "'").replace(/\s+/g, " ");
    out[`.claude/agents/${expertSlug(e)}.md`] = [
      "---",
      `name: ${expertSlug(e)}`,
      `description: "${description}"`,
      "model: inherit",
      "---",
      "",
      w.agentNote,
      "",
      buildExpertPrompt({ ...s, format: "ChatGPT Markdown" }, id),
      "",
    ].join("\n");
  }
  return out;
}

/** .cursor/rules/<slug>.mdc — Cursor's current project-rules format (always applied). */
export function exportCursorMdc(s: StudioState): string {
  const title = s.lang === "TR" ? `${s.name} — proje kuralları` : `${s.name} — project rules`;
  return ["---", `description: ${s.name} — build rules (Prompt.Monster)`, "globs:", "alwaysApply: true", "---", "", exportAgentsMd(s, title)].join("\n");
}

/** .taskmaster/docs/prd.txt — Task Master's PRD template, filled (then: task-master parse-prd). */
export function exportTaskMasterPrd(s: StudioState): string {
  const tr = s.lang === "TR";
  const w = W[s.lang];
  const comp = s.competitors.filter(Boolean);
  const feat = s.features.length ? s.features : [tr ? "Çekirdek akış" : "Core flow"];
  const mvp = feat.slice(0, Math.min(feat.length, 8));
  const later = feat.slice(mvp.length);
  const pay = s.payments.length ? paymentNames(s.payments) : "";
  const lines: (string | null)[] = [
    "<context>",
    "# Overview",
    `${s.name} — ${s.pitch}`,
    s.description ? "" : null,
    s.description || null,
    "",
    s.audience.role ? `${tr ? "Kimin için" : "For"}: ${s.audience.role}. ${tr ? "Problem" : "Problem"}: ${s.audience.pain}. ${tr ? "Bütçe" : "Budget"}: ${s.audience.budget}.` : null,
    s.usp ? `${tr ? "Değer / farklılık" : "Value / differentiation"}: ${s.usp}` : null,
    "",
    "# Core Features",
    ...feat.map((f, i) => `${i + 1}. ${f}`),
    "",
    tr
      ? `Her özellik için: kullanıcı hikâyesi, ölçülebilir kabul kriterleri, API + UI + test. Her biri şu vaade hizmet etmeli: "${s.pitch || s.name}".`
      : `For every feature: a user story, measurable acceptance criteria, API + UI + tests. Each must serve the promise: "${s.pitch || s.name}".`,
    "",
    "# User Experience",
    s.audience.role ? `- Persona: ${s.audience.role}${s.audience.pain ? ` — ${s.audience.pain}` : ""}` : null,
    `- ${tr ? "Ana akışlar" : "Key flows"}: ${(tr ? ["Kayıt ve ilk değer (aha anı)", ...mvp.slice(0, 2)] : ["Sign-up to first value (aha moment)", ...mvp.slice(0, 2)]).join(" → ")}`,
    `- UI/UX: ${tr ? "klavye öncelikli, boş/hata/yükleniyor durumları, erişilebilir (WCAG AA), mobil uyumlu" : "keyboard-first, empty/error/loading states, accessible (WCAG AA), responsive"}`,
    "</context>",
    "<PRD>",
    "# Technical Architecture",
    ...stackLines(s),
    `- ${tr ? "Veri modeli" : "Data model"}: ${tr ? "kullanıcı/organizasyon, çekirdek varlıklar, denetim kaydı; kullanıcı verisinde RLS" : "users/organizations, core entities, audit log; RLS on user data"}`,
    pay ? `- ${w.payments}: ${pay} → webhook → background job → entitlement → audit log` : null,
    s.compliance.length ? `- ${w.compliance}: ${s.compliance.join(", ")}` : null,
    "",
    "# Development Roadmap",
    "## MVP",
    tr ? "- Temel: kimlik doğrulama, veritabanı şeması + migration'lar, uygulama iskeleti ve düzen" : "- Foundation: authentication, database schema + migrations, app shell and layout",
    ...mvp.map((f) => `- ${f}`),
    pay ? (tr ? `- Ödeme ve plan yetkileri (${pay})` : `- Billing and plan entitlements (${pay})`) : null,
    ...(later.length ? ["", tr ? "## Sonraki aşama" : "## Future enhancements", ...later.map((f) => `- ${f}`)] : []),
    "",
    "# Logical Dependency Chain",
    tr ? "1. Temel: auth, şema, iskelet" : "1. Foundation: auth, schema, app shell",
    tr ? `2. Görünür ilk değer: ${mvp[0]}` : `2. First visible value: ${mvp[0]}`,
    ...mvp.slice(1).map((f, i) => `${i + 3}. ${f}`),
    tr ? `${mvp.length + 2}. Ödeme, analitik, lansman kontrol listesi` : `${mvp.length + 2}. Billing, analytics, launch checklist`,
    "",
    "# Risks and Mitigations",
    ...(tr
      ? [
          "- Kapsam kayması → MVP listesi dışındaki her şey 'Sonraki aşama'ya.",
          "- Güvenlik/uyumluluk → RLS, sunucuda yetki, gizli anahtarlar ortam değişkeninde; uyumluluk kontrol listesi.",
          "- Ödeme hataları → idempotent webhook'lar, test modu, abonelik durum makinesi.",
          "- Performans → p95 < 100 ms bütçesi, önbellek, N+1 yok.",
        ]
      : [
          "- Scope creep → anything not in the MVP list goes to Future enhancements.",
          "- Security/compliance → RLS, server-side authorization, secrets in env vars; a compliance checklist.",
          "- Payment bugs → idempotent webhooks, test mode, a subscription state machine.",
          "- Performance → a p95 < 100 ms budget, caching, no N+1 queries.",
        ]),
    "",
    "# Appendix",
    comp.length ? `- ${w.competitors}: ${comp.join(", ")}` : null,
    s.monetization.length ? `- ${w.money}: ${s.monetization.join(", ")}` : null,
    `- ${tr ? "Uzmanlar" : "Experts"}: ${s.experts.map((id) => EXPERTS.find((e) => e.id === id)?.role ?? id).join(", ")}`,
    `- Mega Chain: ${MEGA_CHAIN_STEPS.join(" → ")}`,
    `- ${tr ? "Kaynak" : "Source"}: Prompt.Monster (prompter.monster)`,
    "</PRD>",
    "",
  ];
  return lines
    .filter((l): l is string => l !== null)
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

export interface ExportFileDef {
  id: string;
  /** Path (relative to the repo root) or a folder for multi-file exports. */
  path: string;
  label: string;
  tool: string;
  desc: { tr: string; en: string };
}

/** The project files a Pro export produces (shown in the Studio and on the developers page). */
export const PROJECT_FILES: ExportFileDef[] = [
  { id: "agents", path: "AGENTS.md", label: "AGENTS.md", tool: "Codex · Cursor · Jules · Amp · Copilot", desc: { tr: "Tüm ajanların okuduğu ortak talimat dosyası", en: "The shared instructions file every agent reads" } },
  { id: "claude", path: "CLAUDE.md", label: "CLAUDE.md", tool: "Claude Code", desc: { tr: "Claude Code her oturumda okur", en: "Read by Claude Code every session" } },
  { id: "claude-agents", path: ".claude/agents/", label: ".claude/agents/*.md", tool: "Claude Code", desc: { tr: "Uzman başına bir alt ajan (subagent)", en: "One subagent per expert" } },
  { id: "cursor-mdc", path: ".cursor/rules/", label: ".cursor/rules/*.mdc", tool: "Cursor", desc: { tr: "Cursor'ın güncel kural formatı", en: "Cursor's current rules format" } },
  { id: "cursorrules", path: ".cursorrules", label: ".cursorrules", tool: "Cursor · Windsurf", desc: { tr: "Klasik kural dosyası", en: "Classic rules file" } },
  { id: "copilot", path: ".github/copilot-instructions.md", label: "copilot-instructions.md", tool: "GitHub Copilot", desc: { tr: "Copilot depo talimatları", en: "Copilot repository instructions" } },
  { id: "taskmaster", path: ".taskmaster/docs/prd.txt", label: "Task Master prd.txt", tool: "Task Master AI", desc: { tr: "PRD → task-master parse-prd ile görevlere", en: "PRD → tasks with task-master parse-prd" } },
  { id: "json", path: "prompt-monster.json", label: "prompt-monster.json", tool: "API / automation", desc: { tr: "Tüm girdi ve prompt'lar yapılandırılmış", en: "All inputs and prompts, structured" } },
];

/** Every project file for a state: path → content. */
export function buildProjectFiles(s: StudioState): Record<string, string> {
  const slug =
    s.name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") || "project";
  return {
    "AGENTS.md": exportAgentsMd(s),
    "CLAUDE.md": exportClaudeMd(s),
    ...exportClaudeAgents(s),
    [`.cursor/rules/${slug}.mdc`]: exportCursorMdc(s),
    ".cursorrules": exportCursorRules(s),
    ".github/copilot-instructions.md": exportCopilotInstructions(s),
    ".taskmaster/docs/prd.txt": exportTaskMasterPrd(s),
    "prompt-monster.json": exportJSON(s),
  };
}
