import type { TypePageCopy } from "./seo-types";

/** English copy for /en/prompt/[slug] — same ids and slugs as the Turkish COPY in seo-types.ts. */
export const COPY_EN: TypePageCopy[] = [
  {
    id: "saas-dash",
    slug: "saas-dashboard",
    name: "SaaS Dashboard",
    title: "Master build prompt for a SaaS dashboard",
    description: "A build prompt that gets Claude Code, Cursor or v0 to ship a multi-tenant SaaS dashboard in one go: auth, RBAC, billing, analytics and ⌘K search included.",
    intro: [
      "The SaaS dashboard is the backbone of most B2B products: teams, roles, subscriptions and usage data all come together on one screen. Telling an AI coding tool \"build me a dashboard\" isn't enough; if decisions like multi-tenancy, RBAC, billing and audit logs aren't made up front, the tool invents a different architecture every time.",
      "Prompt.Monster walks you through those decisions, combines them with the perspectives of 12 expert personas and generates a master build prompt you can paste straight into Claude Code, Cursor, v0, Lovable or Bolt.",
    ],
    audience: "Indie hackers, agencies and product teams building B2B SaaS",
    samplePitch: "A Linear-fast, multi-tenant SaaS admin dashboard for small teams",
    sampleDescription: "Teams manage their projects, members and subscriptions from a single dashboard. Role-based permissions, ⌘K search, real-time notifications and usage-based billing. First goal: 100 paying teams.",
    faq: [
      { q: "Which multi-tenancy approach does the prompt recommend?", a: "It asks for a tenant_id + Row Level Security model on Postgres, with organizations handled through Clerk or Supabase Auth, and adds a hard constraint that every query is written with a tenant filter." },
      { q: "Is billing covered in the prompt?", a: "Yes. Subscription, webhook and customer-portal flows for the provider you choose (Stripe, Paddle, Lemon Squeezy, Iyzico…) get their own task block in the 'Auth & Billing' step." },
    ],
    keywords: ["saas dashboard prompt", "saas admin panel build prompt", "cursor saas dashboard prompt", "claude code saas prompt", "multi-tenant saas next.js"],
  },
  {
    id: "ai-wrapper",
    slug: "ai-saas-wrapper",
    name: "AI SaaS Wrapper",
    title: "Master build prompt for an AI SaaS wrapper",
    description: "A build prompt for an LLM-powered SaaS (chat, RAG, agents) with credit quotas, streaming and cost control. Claude, GPT-4o, Groq and vector DB picks included.",
    intro: [
      "With AI wrappers, the edge isn't the model, it's the product around it: quotas and credits, a streaming UI, RAG quality, margins over inference cost and abuse protection. Leave these out of your prompt and your AI coding tool will ship nothing more than a chat box.",
      "The prompt template on this page puts the AI Engineer and Monetization Strategist up front: model choice, vector database, token budget, credit-based pricing and an evaluation (evals) plan, all in one document.",
    ],
    audience: "Founders and vibe coders who want to ship an AI product",
    samplePitch: "Upload your docs, ask in plain English: a RAG-powered knowledge assistant for small businesses",
    sampleDescription: "Users upload PDF and Word files; the system chunks them, writes them to a vector DB and answers with Claude, citing its sources. Credit-based quotas, team sharing, streaming responses and answer-quality scoring.",
    faq: [
      { q: "Which model should I start with?", a: "The prompt recommends Claude 3.5 Sonnet for quality and Llama 3 on Groq for speed and cost, and asks for a provider layer that abstracts both, so switching models later is a one-file change." },
      { q: "Do I need a vector database for RAG?", a: "For small datasets, Postgres + pgvector is enough; the prompt makes it the default and marks the point in the architecture where you'd move to Qdrant or Pinecone." },
    ],
    keywords: ["ai saas build prompt", "rag app prompt", "chatgpt wrapper saas", "claude api saas prompt", "ai wrapper app cursor"],
  },
  {
    id: "plg",
    slug: "plg-product",
    name: "PLG Product",
    title: "Master build prompt for a Product-Led Growth (PLG) product",
    description: "The build prompt for a PLG product that grows through no-signup trials, self-serve onboarding, referrals and usage-based upgrade flows.",
    intro: [
      "PLG products have no sales team; the product sells itself. That's why the onboarding tour, the shortest path to the 'aha' moment, referral credits and the upgrade screen that appears when users hit a usage limit all have to be designed from day one.",
      "In this prompt, the Growth Architect and Product Manager personas define activation metrics, experimentation infrastructure and pricing tiers; the CTO persona wires them into the architecture with event tracking and feature flags.",
    ],
    audience: "SaaS teams building a self-serve growth model",
    samplePitch: "A task automation tool for teams that starts free and grows with usage",
    sampleDescription: "First automation without signing up, save it with just an email, 3-minute onboarding, an upgrade prompt at the usage limit and credits for everyone who invites a teammate. Activation and expansion metrics are measured in-product.",
    faq: [
      { q: "Which PLG metrics go into the prompt?", a: "Activation rate, time to value (TTV), weekly active teams and expansion MRR; the prompt asks for the event schema and a dashboard for each of them." },
      { q: "Freemium or free trial?", a: "The Monetization Strategist gives a reasoned recommendation based on your product type; on the PLG page the default is freemium plus usage-based upgrades." },
    ],
    keywords: ["plg saas prompt", "product led growth build prompt", "self-serve saas onboarding", "freemium saas build prompt"],
  },
  {
    id: "chrome-ext",
    slug: "chrome-extension",
    name: "Chrome Extension + App",
    title: "Master build prompt for a Chrome extension + web app",
    description: "A build prompt that ships a Manifest V3 Chrome extension together with its companion web app: accounts, sync and billing.",
    intro: [
      "Extension products come in two parts: the Manifest V3 extension in the browser and the web app that handles accounts, billing and sync. Authentication, messaging and version compatibility between the two are where most builds go wrong.",
      "This prompt spells out the service worker / content script boundaries, the permission justifications the Chrome Web Store expects and the session model shared with the web app.",
    ],
    audience: "Developers building in-browser productivity and AI tools",
    samplePitch: "A Chrome extension that summarizes any web page in one click and saves it to your notes",
    sampleDescription: "A content script grabs the page text, the service worker sends it to the API and notes sync to the web app. Free: 10 summaries/day; Pro: unlimited. A permission set that follows Chrome Web Store review policies.",
    faq: [
      { q: "Does the prompt cover Manifest V3 restrictions?", a: "Yes: the ban on remotely hosted code, the service worker lifecycle, host permission justifications and declarativeNetRequest usage are all in the constraints section." },
      { q: "How is the session shared between the extension and the web app?", a: "The prompt defines storing a short-lived token issued by the web app in chrome.storage, along with the refresh flow." },
    ],
    keywords: ["chrome extension build prompt", "manifest v3 extension prompt", "chrome extension saas", "cursor chrome extension prompt", "claude code chrome extension"],
  },
  {
    id: "headless",
    slug: "headless-e-ticaret",
    name: "Headless E-commerce",
    title: "Master build prompt for a headless e-commerce store",
    description: "A fast, SEO-ready storefront on Next.js + headless commerce: product catalog, cart, Stripe or Iyzico/PayTR checkout and search. Build prompt ready.",
    intro: [
      "Headless e-commerce splits the storefront from the backend: catalog, inventory and orders come from an API, while the Next.js storefront loads in milliseconds, not seconds. Payments and invoicing are critical: Stripe for global sales, plus Iyzico, PayTR and e-invoicing (e-Fatura) if you sell in Turkey.",
      "The prompt brings the product-variant model, the cart/checkout state machine, search (Algolia/Typesense) and SEO requirements (structured data, sitemap, Core Web Vitals) together in a single document.",
    ],
    audience: "Brands, agencies and teams moving from Shopify to headless",
    samplePitch: "A fast, SEO-first headless storefront for a fashion brand",
    sampleDescription: "Catalog and inventory come from a headless API; the storefront runs on Next.js ISR. Products with variants, promotion rules, Stripe checkout with 3D Secure, an e-invoicing webhook, Typesense search and an LCP < 1.5 s target.",
    faq: [
      { q: "Which payment provider should I choose?", a: "Stripe for international sales, Iyzico or PayTR if you sell in Turkey; the prompt connects both to the same payment abstraction layer." },
      { q: "What does the prompt include for SEO?", a: "Product schema (JSON-LD), canonical URLs, a sitemap, image optimization and Core Web Vitals targets all sit in the SEO/AEO Strategist's task block." },
    ],
    keywords: ["headless ecommerce prompt", "next.js ecommerce build prompt", "headless storefront next.js", "stripe checkout integration prompt", "claude code ecommerce store"],
  },
  {
    id: "marketplace",
    slug: "multi-vendor-marketplace",
    name: "Multi-Vendor Marketplace",
    title: "Master build prompt for a multi-vendor marketplace",
    description: "The build prompt for a multi-vendor marketplace with seller onboarding, commissions, split payments, order management and search.",
    intro: [
      "A marketplace has three sides: buyers, sellers and the platform. Seller onboarding, commissions and split payments, dispute handling and search quality are the complex pieces that decide whether the product succeeds.",
      "This prompt defines the seller dashboard, the platform admin and the buyer experience as separate roles, and adds your payment provider's split/escrow capabilities and GDPR/KVKK obligations to the constraints.",
    ],
    audience: "Founders building niche marketplaces",
    samplePitch: "A commission-based handmade goods marketplace for local artisans",
    sampleDescription: "Seller applications and approval, shop pages, order and shipment tracking, buyer-seller messaging, split payments with an 8% commission, a review system and a dispute flow.",
    faq: [
      { q: "How are split payments handled?", a: "The prompt calls for Stripe Connect (or the Iyzico Marketplace model in Turkey) and defines payment, commission deduction and payout to the seller as a state machine." },
      { q: "How detailed is seller onboarding?", a: "Application, document verification, store setup and first-product steps are all covered in the Product Manager persona's user stories." },
    ],
    keywords: ["marketplace build prompt", "multi vendor marketplace prompt", "stripe connect marketplace", "claude code marketplace prompt", "cursor marketplace app prompt"],
  },
  {
    id: "d2c",
    slug: "d2c-abonelik-kutusu",
    name: "D2C Subscription Box",
    title: "Master build prompt for a D2C subscription box",
    description: "The build prompt for D2C subscription e-commerce: monthly box plans, a preference quiz, delivery schedules and churn-reduction flows.",
    intro: [
      "In the subscription box business, the technical challenge isn't the catalog; it's recurring billing and the logistics calendar. Skip-a-month, address changes, box personalization and cancellation-prevention flows drive most of the revenue.",
      "The prompt explicitly defines the subscription lifecycle (trial → active → paused → canceled) and the emails and notifications each transition triggers.",
    ],
    audience: "D2C brands and subscription box startups",
    samplePitch: "A monthly personalized roast subscription box for coffee lovers",
    sampleDescription: "Personalization via a taste quiz, monthly renewals, skip-a-month, shipment tracking, box ratings and a free box for every friend you refer. A discount-offer flow before cancellation.",
    faq: [
      { q: "How do recurring payments work?", a: "Payments sit behind an abstraction layer: Stripe for global customers, with Iyzico's card storage and subscription product as the default when you sell in Turkey." },
      { q: "Does the prompt include a churn-reduction flow?", a: "Yes. The Growth Architect persona writes a cancellation-reason survey, a pause option and a win-back campaign into its task block." },
    ],
    keywords: ["subscription box website prompt", "d2c subscription build prompt", "subscription ecommerce app prompt", "monthly subscription box software"],
  },
  {
    id: "b2b",
    slug: "b2b-toptan-portal",
    name: "B2B Wholesale Portal",
    title: "Master build prompt for a B2B wholesale portal",
    description: "The build prompt for a B2B portal with dealer accounts, customer-specific price lists, account balances, order approvals and ERP integration.",
    intro: [
      "In a B2B portal, every customer sees different prices, payment terms and approval chains. Account balances, quote-to-order conversion and ERP sync call for a data model that's completely different from B2C e-commerce.",
      "The prompt brings customer groups, price lists, minimum order rules, payment-term and credit-limit tracking and ERP webhooks together in a single architecture.",
    ],
    audience: "Wholesalers, distributors and manufacturers",
    samplePitch: "A wholesale ordering portal for dealers with customer-specific pricing and on-account billing",
    sampleDescription: "Dealer approval, price list groups, minimum order quantities, payment-term and credit-limit checks, an order approval chain, e-invoicing and ERP sync (NetSuite / SAP Business One), and a sales rep dashboard.",
    faq: [
      { q: "How is ERP integration handled?", a: "The prompt asks for a sync service that treats the ERP as the single source of truth, plus an idempotent webhook consumer." },
      { q: "Isn't customer-specific pricing complicated?", a: "The price list + customer group + quantity tier model comes ready in the data schema, and the CTO persona provides an example table structure." },
    ],
    keywords: ["b2b portal build prompt", "wholesale ordering portal prompt", "b2b ecommerce build prompt", "dealer portal software"],
  },
  {
    id: "neobank",
    slug: "neobank-dashboard",
    name: "Neobank Dashboard",
    title: "Master build prompt for a neobank / fintech dashboard",
    description: "A build prompt for a neobank app with accounts, cards, transfers and spending analytics, written with security and compliance constraints.",
    intro: [
      "In fintech, the most expensive mistakes are security mistakes: if KYC, 2FA, transaction limits, audit trails and PCI scope aren't considered in the first version, you'll end up rewriting them later.",
      "The prompt puts the Security & Compliance and Data Engineer personas up front, defining encryption for sensitive data, a transaction ledger model, double-entry accounting and suspicious-transaction rules.",
    ],
    audience: "Fintech startups and bank innovation teams",
    samplePitch: "A neobank dashboard for freelancers that tracks income, expenses and taxes",
    sampleDescription: "Account linking via open banking, spending categorization, invoice and tax estimates, card limits, 2FA/passkeys, a transaction audit trail and anomaly alerts.",
    faq: [
      { q: "Why does the ledger model matter?", a: "Instead of storing the balance as a single number, the prompt makes a double-entry transaction ledger a hard constraint, which is what makes reconciliation and audits possible." },
      { q: "How do I reduce my PCI scope?", a: "Never storing card data and relying on your provider's tokenization are written explicitly into the constraints section." },
    ],
    keywords: ["fintech dashboard prompt", "neobank app build prompt", "banking app cursor prompt", "fintech app claude code"],
  },
  {
    id: "crypto",
    slug: "crypto-defi-tracker",
    name: "Crypto/DeFi Tracker",
    title: "Master build prompt for a crypto / DeFi portfolio tracker",
    description: "The build prompt for a crypto app with wallet connections, multi-chain portfolios, price alerts and DeFi position tracking.",
    intro: [
      "With crypto trackers, the hard part is the data: multiple chains, on-chain data providers, price feeds and rate limits. Without a real-time update and caching strategy, the product ends up either slow or expensive.",
      "The prompt defines a data-provider abstraction, a WebSocket price stream, an alert engine and accuracy constraints for portfolio calculations (cost basis, PnL).",
    ],
    audience: "Web3 developers and teams building investment tools",
    samplePitch: "A portfolio tool that tracks multi-chain wallets in one dashboard and sends alerts",
    sampleDescription: "Add wallet addresses, Ethereum/Solana/BSC balances, DeFi positions, price and liquidation alerts, PnL charts and tax report export. A cache that holds up against provider rate limits.",
    faq: [
      { q: "Which data providers are recommended?", a: "The prompt asks for a layer that abstracts the provider; the examples given are CoinGecko for prices, Alchemy/Helius for on-chain data and a WebSocket stream." },
      { q: "What about the risk of giving investment advice?", a: "The constraints section makes copy stating that the product is for informational purposes only, along with legal disclaimers, mandatory." },
    ],
    keywords: ["crypto portfolio tracker prompt", "defi tracker build prompt", "web3 dashboard prompt", "multi-chain wallet tracker app"],
  },
  {
    id: "invoice",
    slug: "fatura-abonelik-saas",
    name: "Invoice & Billing SaaS",
    title: "Master build prompt for an invoicing & subscription management SaaS",
    description: "The build prompt for a billing SaaS with invoice creation, e-invoicing, payment tracking, recurring invoices and a customer portal.",
    intro: [
      "In billing products, accuracy is everything: VAT calculations, currency rounding, e-invoice/e-archive integration and payment reconciliation. One small bug means accounting chaos.",
      "The prompt defines the invoice state machine, tax and rounding rules, e-invoicing integrator webhooks (such as Turkey's GİB integrators) and the customer portal (view, pay, download) in a single architecture.",
    ],
    audience: "Startups building tools for freelancers and small businesses",
    samplePitch: "An invoicing tool for freelancers and agencies with e-invoicing support and payment tracking",
    sampleDescription: "Client profiles, quote → invoice conversion, recurring invoices, e-invoice/e-archive submission, online payment links, overdue reminders and revenue reports.",
    faq: [
      { q: "How does the prompt handle e-invoicing integration?", a: "Submission, status checks and retry-on-error flows for an e-invoicing integrator API (e.g. a GİB-accredited private integrator in Turkey) are included as a separate task." },
      { q: "What about money and rounding rules?", a: "Amounts are stored as integers in minor units (cents) and VAT is calculated per line item — both are mandatory in the constraints section." },
    ],
    keywords: ["invoicing software prompt", "invoice saas build prompt", "billing app cursor prompt", "e-invoicing saas", "recurring invoice app"],
  },
  {
    id: "social",
    slug: "sosyal-ag",
    name: "Social Network",
    title: "Master build prompt for a social network / community app",
    description: "The build prompt for a social network app with feeds, follows, real-time notifications, moderation and content recommendations.",
    intro: [
      "With social products, the hard part is keeping your first 100 users: feed ranking, notification cadence, moderation and content quality. On the technical side, fan-out, caching and real-time updates surface scaling problems early.",
      "The prompt defines the feed architecture (fan-out on write/read), moderation tools, the reporting flow and growth loops (invites, sharing).",
    ],
    audience: "Teams building niche communities and social apps",
    samplePitch: "A route-sharing, event-based social network for local runners",
    sampleDescription: "Profiles, follows, route posts (GPX + photos), comments and likes, event creation, real-time notifications, a moderation dashboard and reporting. An invite-driven growth loop.",
    faq: [
      { q: "How is feed ranking defined?", a: "It starts with a simple chronological, follow-weighted score; the prompt marks the point where you'd move to engagement-based ranking next." },
      { q: "Is moderation included in the prompt?", a: "Reporting, automated filters, a moderator queue and user sanctions are in the Security & Compliance persona's task block." },
    ],
    keywords: ["social network app prompt", "community platform build prompt", "social media app cursor prompt", "claude code social app"],
  },
  {
    id: "creator",
    slug: "creator-economy",
    name: "Creator Economy",
    title: "Master build prompt for a creator economy platform",
    description: "The build prompt for a creator platform with subscriptions, digital product sales, membership tiers and creator payouts.",
    intro: [
      "Creator platforms serve two customers: the creator and the fan. Membership tiers, payouts, content access control and the discovery flow all have to work at the same time.",
      "The prompt combines Substack- and Gumroad-style models in a single product: a page builder, tiered subscriptions, digital product delivery, commissions and payouts.",
    ],
    audience: "Builders of creator tools and membership platforms",
    samplePitch: "A membership and digital products platform for independent podcasters and newsletter writers",
    sampleDescription: "Creator pages, free/paid tiers, access control for episodes and posts, digital product sales (PDFs, courses), a 10% commission, monthly payouts and creator analytics.",
    faq: [
      { q: "How are creator payouts handled?", a: "The prompt defines Stripe Connect (or Iyzico's sub-merchant model in Turkey) for paying creators after the platform commission is deducted, plus monthly reconciliation." },
      { q: "How is content access controlled?", a: "Tier-based authorization, signed media URLs and preview rules are part of the CTO and Security & Compliance tasks." },
    ],
    keywords: ["creator platform build prompt", "membership platform prompt", "substack clone", "gumroad alternative build prompt", "creator economy app"],
  },
  {
    id: "jobboard",
    slug: "job-board-ats",
    name: "Job Board ATS",
    title: "Master build prompt for a job board + ATS",
    description: "The build prompt for a job board with job posting, application management, applicant tracking (ATS), employer packages and SEO-ready job pages.",
    intro: [
      "Job boards balance two sides: employers want to manage listings and candidates, while candidates want quick applications and visibility. Programmatic SEO job pages are the engine of organic traffic.",
      "The prompt defines the job listing lifecycle, the application pipeline (Kanban), employer packages and billing, and structured data for job pages (JobPosting schema).",
    ],
    audience: "Builders of niche job boards and HR tools",
    samplePitch: "A job board and mini ATS for remote software developers",
    sampleDescription: "Employer sign-up, job post package purchases, publishing listings, candidate applications with CV upload, Kanban candidate tracking, email notifications and SEO pages with JobPosting schema.",
    faq: [
      { q: "How does the prompt handle SEO job pages?", a: "Canonical URLs and JobPosting JSON-LD for every listing, the sitemap and the handling of expired listings are the SEO/AEO Strategist persona's task." },
      { q: "What about candidate data and GDPR/KVKK?", a: "Retention periods, deletion requests and a privacy notice are mandatory in the constraints section." },
    ],
    keywords: ["job board build prompt", "ats software prompt", "job board saas", "niche job board cursor prompt", "applicant tracking system app"],
  },
  {
    id: "edtech",
    slug: "edtech-lms",
    name: "EdTech LMS",
    title: "Master build prompt for an EdTech LMS / online course platform",
    description: "The build prompt for an LMS with course creation, video lessons, quizzes, progress tracking, certificates and subscriptions.",
    intro: [
      "In online learning products, the learning experience matters as much as content management: progress tracking, quizzes and feedback, certificates and community. Video hosting and protection are a real cost line, too.",
      "The prompt defines the course-module-lesson hierarchy, video delivery (signed URLs, HLS), the quiz engine, certificate generation and instructor revenue sharing.",
    ],
    audience: "EdTech startups, instructors and corporate academies",
    samplePitch: "A project-based course platform for software developers",
    sampleDescription: "Instructors create courses and add video lessons and quizzes; students get progress tracking, certificates, Q&A and a choice of monthly subscription or single-course purchase; instructor revenue sharing and analytics.",
    faq: [
      { q: "What's recommended for video hosting?", a: "Signed playback via Cloudflare Stream or Mux; the prompt includes constraints that make downloading harder, plus a cost estimate." },
      { q: "How are certificates generated?", a: "Completion criteria and PDF certificate generation (with a verification link) are part of the Product Manager and CTO tasks." },
    ],
    keywords: ["lms build prompt", "online course platform prompt", "edtech saas", "lms app cursor prompt", "course platform claude code"],
  },
  {
    id: "health",
    slug: "telemedicine",
    name: "HealthTech Telemedicine",
    title: "Master build prompt for a telemedicine / online health platform",
    description: "A privacy-first build prompt for a telemedicine product with appointments, video visits, patient records, e-prescriptions and payments.",
    intro: [
      "In health products, data privacy and access control sit at the center of the design. Appointments, video call quality and the accuracy of clinical records determine whether users trust you.",
      "The prompt defines patient and doctor roles, the appointment and consultation flow, record encryption, an access audit trail and GDPR/KVKK obligations for special-category health data.",
    ],
    audience: "Health startups, clinic chains and digital health teams",
    samplePitch: "A video consultation platform with online booking for dietitians and psychologists",
    sampleDescription: "Practitioner profiles and calendars, booking and payment, video calls (WebRTC), session notes and file sharing, reminders, and encryption plus access logging for special-category data.",
    faq: [
      { q: "How is special-category health data protected?", a: "Application-level encryption, the principle of least privilege, an access audit trail and data retention periods are mandatory in the constraints section." },
      { q: "What's recommended for video calls?", a: "WebRTC providers such as Daily or Twilio, or self-hosted LiveKit; the prompt lays out the quality/cost trade-off with its reasoning." },
    ],
    keywords: ["telemedicine app build prompt", "telehealth platform prompt", "healthtech saas", "video consultation app prompt"],
  },
  {
    id: "proptech",
    slug: "proptech-emlak",
    name: "PropTech Real Estate",
    title: "Master build prompt for a PropTech / real estate platform",
    description: "The build prompt for a real estate platform with property listings, map search, virtual tours, an agent CRM and a rental flow.",
    intro: [
      "On real estate platforms, the discovery experience makes or breaks the product: map-based filtering, saved searches, price alerts and high-quality media. On the agent side, you need listing management and lead tracking.",
      "The prompt defines geo search (PostGIS), media processing, listing verification, lead routing and SEO-optimized listing and neighborhood pages.",
    ],
    audience: "Real estate startups and brokerage networks",
    samplePitch: "A verified room and apartment rental platform for students",
    sampleDescription: "Map-based search and filters, listing verification, photos and virtual tours, saved searches and price alerts, landlord-tenant messaging, agent packages and neighborhood SEO pages.",
    faq: [
      { q: "How is map search built?", a: "Bounding-box/radius queries and clustering with PostGIS; the prompt adds indexing constraints for query performance." },
      { q: "How do neighborhood pages help SEO?", a: "Auto-generated content and structured data for every neighborhood through programmatic SEO are the SEO/AEO Strategist persona's task." },
    ],
    keywords: ["real estate platform build prompt", "proptech app prompt", "rental listing website prompt", "zillow clone prompt", "property listing app cursor"],
  },
  {
    id: "logistics",
    slug: "lojistik-takip",
    name: "Logistics Tracking",
    title: "Master build prompt for a logistics & shipment tracking platform",
    description: "The build prompt for a logistics product with shipment creation, courier/vehicle tracking, route optimization, proof of delivery and customer alerts.",
    intro: [
      "In logistics software, real-time location, status transitions and exception handling (address not found, damaged goods) are the heart of the product. The field app and the operations dashboard have to share the same data.",
      "The prompt defines the shipment state machine, the driver's mobile flow, route optimization, proof of delivery (photo/signature) and the customer tracking page.",
    ],
    audience: "Shipping, courier and field operations teams",
    samplePitch: "A live tracking and proof-of-delivery platform for urban courier networks",
    sampleDescription: "Shipment creation and labels, courier assignment, live location, route suggestions, delivery photo/signature, customer tracking links and SMS notifications, exception handling and operations reports.",
    faq: [
      { q: "What's the architecture for live location?", a: "Periodic location updates from the mobile client, broadcast to the operations dashboard over WebSocket, and a time-series table; the prompt adds battery and data-usage constraints." },
      { q: "Is route optimization included?", a: "Initially through an external API (e.g. Mapbox Optimization); the prompt marks the point where you'd switch to your own solver." },
    ],
    keywords: ["delivery tracking software prompt", "logistics platform build prompt", "courier tracking saas", "proof of delivery app", "fleet tracking app prompt"],
  },
  {
    id: "ondemand",
    slug: "on-demand-uber-benzeri",
    name: "On-Demand Uber-like",
    title: "Master build prompt for an on-demand (Uber-like) services app",
    description: "The build prompt for an on-demand app with customer, provider and operator roles: matching, live tracking, payments and ratings.",
    intro: [
      "On-demand products are really three apps: the customer app, the provider app and the operations dashboard. The matching algorithm, real-time location and the payment/commission flow are the hardest parts of the product.",
      "The prompt defines the request-matching state machine, driver/provider onboarding, live tracking and payouts in a mobile-first architecture.",
    ],
    audience: "Startups building local services marketplaces",
    samplePitch: "An on-demand matching app for home care and cleaning services",
    sampleDescription: "Customers post a request and get matched with nearby providers; live tracking and messaging, card payments and commission, two-way ratings, an operations dashboard and a dispute flow.",
    faq: [
      { q: "How does the matching algorithm start out?", a: "With simple scoring weighted by distance, availability and rating; the prompt adds data-collection constraints so you can move to a learning model over time." },
      { q: "Mobile app or web?", a: "A single React Native (Expo) codebase is the default; the prompt defines the web operations dashboard separately in Next.js." },
    ],
    keywords: ["uber clone prompt", "on-demand app build prompt", "uber-like app prompt", "service marketplace app prompt", "react native on-demand app"],
  },
  {
    id: "booking",
    slug: "booking-rezervasyon-saas",
    name: "Booking SaaS",
    title: "Master build prompt for an appointment & booking SaaS",
    description: "The build prompt for a booking SaaS with calendars, availability rules, an online booking page, reminders and payments or deposits.",
    intro: [
      "In scheduling products, the complexity lives in the calendar: time zones, buffer times, resource/room conflicts, cancellation policies and Google Calendar sync. Get it wrong and double bookings are inevitable.",
      "The prompt defines the availability engine, the booking state machine, the reminder and no-show flow, deposit/cancellation rules and a public booking page for each business.",
    ],
    audience: "Builders of tools for hair salons, clinics, studios and consultancies",
    samplePitch: "Per-staff calendars and an online booking page for beauty salons",
    sampleDescription: "Service and staff setup, availability rules, a public booking page, SMS/email reminders, deposits and a cancellation policy, Google Calendar sync and business reports.",
    faq: [
      { q: "How are double bookings prevented?", a: "A database-level exclusion constraint plus optimistic locking are mandatory constraints in the prompt." },
      { q: "How are time zones handled?", a: "All times are stored in UTC, with the business's and the customer's time zones kept separately; the prompt spells this out in the data model." },
    ],
    keywords: ["booking system build prompt", "appointment booking saas prompt", "online booking software prompt", "calendly clone prompt", "scheduling app cursor prompt"],
  },
  {
    id: "crm",
    slug: "crm-erp",
    name: "CRM/ERP",
    title: "Master build prompt for a CRM / lightweight ERP",
    description: "The build prompt for a CRM/ERP with customer records, a sales pipeline, a quote-to-order-to-invoice flow, tasks and reports.",
    intro: [
      "In CRM/ERP products, the data model and permission matrix are half the work: customers, deals, quotes, orders, invoices and inventory are all linked, and every role sees and edits something different.",
      "The prompt defines the core entity model, the sales pipeline flow, custom fields, bulk actions, and reporting and import/export requirements.",
    ],
    audience: "Teams building vertical CRM/ERP software for SMBs",
    samplePitch: "A lightweight quote-to-order-to-invoice CRM/ERP for building materials dealers",
    sampleDescription: "Contact and company records, a deals Kanban, quote creation and conversion to orders, inventory and price lists, e-invoicing, tasks and reminders, sales reports and Excel import/export.",
    faq: [
      { q: "How are custom fields modeled?", a: "A flexible JSONB-based field schema plus validation rules; the prompt adds indexing constraints so the fields stay reportable." },
      { q: "How do I migrate existing Excel data?", a: "An import wizard, field mapping and an error report are covered in the Product Manager persona's user stories." },
    ],
    keywords: ["crm build prompt", "erp build prompt", "small business crm saas", "custom crm cursor prompt", "claude code crm"],
  },
  {
    id: "nocode",
    slug: "no-code-builder",
    name: "No-Code Builder",
    title: "Master build prompt for a no-code site & form builder",
    description: "The build prompt for a no-code builder with a drag-and-drop editor, templates, publishing, custom domains and subscriptions.",
    intro: [
      "In no-code products, the editor experience is the product: the block model, undo, real-time preview and the publishing pipeline. Custom domains and SSL automation are serious infrastructure work, too.",
      "The prompt defines the block/schema-based content model, the editor architecture, publishing (static generation + CDN), the custom domain flow and plan-based limits.",
    ],
    audience: "Product teams building site, form or app builders",
    samplePitch: "A no-code builder that gets a small business website live in 10 minutes",
    sampleDescription: "Template selection, a block-based editor, real-time preview, forms with submission notifications, one-click publishing, custom domains with automatic SSL, plan limits and site analytics.",
    faq: [
      { q: "What does the publishing architecture look like?", a: "Static output + CDN (Cloudflare) with a version for every publish; the prompt asks for rollback and cache-purge flows." },
      { q: "How are custom domains and SSL handled?", a: "CNAME verification and automatic certificates (Cloudflare for SaaS) are the DevOps / SRE persona's task." },
    ],
    keywords: ["no-code builder prompt", "website builder saas build prompt", "form builder app prompt", "webflow alternative build prompt", "drag and drop site builder"],
  },
];
